### ISSUE TITLE
BubbleUpnp can't see upmpdcli renderer

### ISSUE THREAD

**Issue by pedgr** [archphile/support#1] opened 2020-05-10 20:41 UTC
After giving the command : "upmpdcli -c /etc/upmpdcli.conf" in order to activate upmpdcli, I receive : ":3:src/mediaserver/contentdirectory.cxx:187::ContentDirectory: not creating entry for gmusic because neither gmusicuser nor gmusicautostart are defined in the configuration
Writing RSA key". 
I can't even give any othe command.

**Comment by archphile** [comment] 2020-05-11 06:40
Everything is OK as per the manual instructions.

Just give **CTRL + C** (and not X - it was a typo already fixed) to end this command (you only need to give it once and not everytime) and after that you will be able to start/stop/enable upmpdcli as usually.

**Comment by pedgr** [comment] 2020-05-11 20:57
I followed your instructions, but I can not start upmpdcli. BubbleUPnP can not find archphile as renderer. I opened upmpdcli.conf and every line starts with #.
I send a printscreen of what I receive when I give the command "upmpdcli -c /etc/upmpdcli.conf".

<img width="960" alt="2020-05-11" src="https://user-images.githubusercontent.com/63900417/81610698-a0546980-93e2-11ea-8ee9-f0e7ec8f925f.png">

**Comment by archphile** [comment] 2020-05-12 08:14
It's impossible that every line of upmpdcli.conf starts with a #. 

The default configuration file is this one:

https://github.com/archphile/packages/blob/master/upmpdcli-archphile/upmpdcli.conf

I suggest you the following:

1. rm -r /var/cache/upmpdcli
2. wget https://raw.githubusercontent.com/archphile/packages/master/upmpdcli-archphile/upmpdcli.conf -O /etc/upmpdcli.conf
3. upmpdcli -c /etc/upmpdcli.conf

after the dots stop appearing, press control + C and you re ready to start/enable/disable the systemd service file

**Comment by pedgr** [comment] 2020-05-12 10:56
I enabled upmpdcli following your instructions.
Unfortunately, BubbleUpnp cannot still find archphile as renderer.
The same problem exists with airplay. I have enabled shairport-sync, but ipad cannot find archphile.
Spotify works flawlessly.
<img width="960" alt="2020-05-12 (1)" src="https://user-images.githubusercontent.com/63900417/81676190-442c2c80-9458-11ea-94d2-0c0fcb1d28f1.png">

**Comment by archphile** [comment] 2020-05-12 11:01
Which board do you use with Archphile?

**Comment by pedgr** [comment] 2020-05-12 11:23
Rpi2B

**Comment by archphile** [comment] 2020-05-12 11:25
It's really strange because I have tested this board a lot in combination with BubbleUpnp.

Have you tried clearing the cache or deleting the data of BubbleUpnp?

**Comment by pedgr** [comment] 2020-05-12 11:45
I have done that.

**Comment by archphile** [comment] 2020-05-12 11:47
I'm sorry, I can't reproduce it. 

Please share your mobile platform and BubbleUpnp version.

**Comment by pedgr** [comment] 2020-05-12 12:29
Android 9 and ios 12.4.3
BubbleUpnp 3.4.6(arm64-v8a)
I enabled umpmdcli and airplay in a rpi3 and so BubbleUpnp, as my ipad,  found archphile renderer immediately.

**Comment by archphile** [comment] 2020-05-13 09:22
So, the issue only happened when using your rpi2 board?
I'm confused. 
Should I close this issue?

**Comment by pedgr** [comment] 2020-05-13 15:45
I'm confused, too.
Everything works perfect with rpi3, but, only spotify works with rpi2.
You can close the issue.
Thank you for your time!

**Closed** 2020-05-13 15:46 UTC
Labels: 1.19 - corona, bug, rpi23
